crimes_list = [{ crime_id: 1, charge: "DUI" },
								{ crime_id: 2, charge: "Sexual harrassment or assault" },
								{ crime_id: 3, charge: "Theft"},
							  { crime_id: 4, charge: "Disorderly conduct"},
							  { crime_id: 5, charge: "Domestic abuse"},
							  { crime_id: 6, charge: "Speeding or reckless driving"},
							  { crime_id: 7, charge: "Weapons possession"},
							  { crime_id: 8, charge: "Drug possession"},
							  { crime_id: 9, charge: "Trespassing"},
							  { crime_id: 10, charge: "Obscenity or indecency violations"},
							  { crime_id: 11, charge: "Prostitution"},
							  { crime_id: 12, charge: "Public intoxication"},
							  { crime_id: 13, charge: "Pedophilia"},
							  { crime_id: 14, charge: "Obstruction of justice"},
							  { crime_id: 15, charge: "Probation violations or contempt"},
							  { crime_id: 16, charge: "Fraud or larceny or forgery"},
							  { crime_id: 17, charge: "Criminal damage"},
							  { crime_id: 18, charge: "Assault"},
							  { crime_id: 19, charge: "Tax evasion"},
							  { crime_id: 20, charge: "Illicit smuggling or selling"},
							  { crime_id: 21, charge: "Animal cruelty"},
							  { crime_id: 22, charge: "Arson"},
							  { crime_id: 23, charge: "Murder"},
							  ]

crimes_list.each do |crime|
  Crime.create(charge: crime[:charge])
end

artists_list = [ { crime: [1] , name: "Aidan Quinn", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/aidan-quinn", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/aquinnmug1_0.jpg" },
{ crime: [1] , name: "Amanda Bynes", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/amanda-bynes", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/amandabynes.jpg" },
{ crime: [2] , name: "Andy Dick '08", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/andy-dick-08", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/andydickmug1.jpg" },
{ crime: [2] , name: "Andy Dick '10", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/andy-dick-10", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/andy2010dickmug1.jpg" },
{ crime: [4] , name: "Andy Dick '11", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/andy-dick-11", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/andydick11mug.jpg" },
{ crime: [1] , name: "Anna Nicole Smith", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/anna-nicole-smith", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/annanicolemug1.jpg" },
{ crime: [2] , name: "Anthony Anderson", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/anthony-anderson", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/aandersonmug1.jpg" },
{ crime: [3] , name: "Brad Renfro", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/brad-renfro", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/renfromug.jpg" },
{ crime: [5] , name: "Carmen Electra", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/carmen-electra", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/electramug.jpg" },
{ crime: [5] , name: "Charlie Sheen", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/charlie-sheen", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/sheenmug1.jpg" },
{ crime: [1] , name: "Chris Klein", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/chris-klein", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/chriskleinmug1.jpg" },
{ crime: [6] , name: "Chris Tucker", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/chris-tucker", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/christuckermug1.jpg" },
{ crime: [7] , name: "Christian Slater", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/christian-slater", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/slatermug.jpg" },
{ crime: [3, 8] , name: "Daniel Baldwin", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/daniel-baldwin", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/baldwinmug1.jpg" },
{ crime: [9] , name: "Daryl Hannah", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/daryl-hannah", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/darylhannah.jpg" },
{ crime: [6] , name: "Dennis Hopper", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/dennis-hopper", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/dhoppermugshot1.jpg" },
{ crime: [4] , name: "Edward Furlong", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/edward-furlong", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/furlongmug1.jpg" },
{ crime: [10] , name: "George Carlin", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/george-carlin", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/gcarlinmug1.jpg" },
{ crime: [1] , name: "Gus Van Sant", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/gus-van-sant", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/vansantmug1.jpg" },
{ crime: [1, 8] , name: "Haley Joel Osment", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/haley-joel-osment", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/osmentmug1.jpg" },
{ crime: [11] , name: "Hugh Grant", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/hugh-grant", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/grantmug1.jpg" },
{ crime: [4] , name: "James Cromwell", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/james-cromwell", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/jamescromwell.jpg" },
{ crime: [4, 20] , name: "Jane Fonda 11/70", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/jane-fonda-1170", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/janefondamug1.jpg" },
{ crime: [20] , name: "Jane Fonda 11/70", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/jane-fonda-1170-0", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/fonda1970mug1.jpg" },
{ crime: [4] , name: "Jason Patric", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/jason-patric", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/jasonpatricmug1.jpg" },
{ crime: [13] , name: "Jeffrey Jones", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/jeffrey-jones", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/jjonesmug1.jpg" },
{ crime: [1] , name: "Jenna Jameson", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/jenna-jameson", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/jennajameson.jpg" },
{ crime: [14] , name: "Josh Brolin '08", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/josh-brolin", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/joshbrolinmug1.jpg" },
{ crime: [4] , name: "Josh Brolin '13", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/josh-brolin-13", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/joshbrolin2013.jpg" },
{ crime: [3, 9] , name: "Katt Williams", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/katt-williams", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/kattwilliamsmug1.jpg" },
{ crime: [1] , name: "Kiefer Sutherland", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/kiefer-sutherland", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/kiefermug1.jpg" },
{ crime: [14] , name: "Lindsay Lohan '11", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/lindsay-lohan-11", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/lindsaylohan2011.jpg" },
{ crime: [6, 14] , name: "Lindsay Lohan '13", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/lindsay-lohan-13", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/lindsaylohan2013.jpg" },
{ crime: [1] , name: "Lindsay Lohan 11/07", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/lindsay-lohan-1107", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/lohan2mug1.jpg" },
{ crime: [1, 8] , name: "Lindsay Lohan 7/07", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/lindsay-lohan-707", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/lohanmug1.jpg" },
{ crime: [15] , name: "Lindsay Lohan 7/10", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/lindsay-lohan-710", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/Lindsay_Lohan.jpg" },
{ crime: [15] , name: "Lindsay Lohan 9/10", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/lindsay-lohan-910", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/lindsaylohan092010.jpg" },
{ crime: [8] , name: "Macaulay Culkin", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/macaulay-culkin", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/culkinmug1.jpg" },
{ crime: [6] , name: "Matt Dillon", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/matt-dillon", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/mattdillonmug1.jpg" },
{ crime: [8] , name: "Matthew McConaughey", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/matthew-mcconaughey", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/mcconaugheymug.jpg" },
{ crime: [1] , name: "Mel Gibson '06", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/mel-gibson-06", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/melgibsonmug1.jpg" },
{ crime: [5] , name: "Mel Gibson '11", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/mel-gibson-11", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/melgibson2011.jpg" },
{ crime: [15] , name: "Michelle Rodriguez", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/michelle-rodriguez", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/mrodriguezmug1.jpg" },
{ crime: [1] , name: "Mickey Rourke", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/mickey-rourke", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/rourkemug1.jpg" },
{ crime: [1] , name: "Natasha Lyonne", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/natasha-lyonne", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/lyonnemug.jpg" },
{ crime: [1] , name: "Nick Nolte '02TSG Fav", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/nick-nolte", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/noltemug.jpg" },
{ crime: [16] , name: "Nick Nolte '61", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/nick-nolte-61", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/nicknolte1961.jpg" },
{ crime: [5] , name: "Nicolas Cage", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/nicolas-cage", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/nicolascage.jpg" },
{ crime: [1] , name: "Nicole Richie", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/nicole-richie", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/nicolerichiemug1.jpg" },
{ crime: [15] , name: "Paris Hilton", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/paris-hilton", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/parismugshot1.jpg" },
{ crime: [8] , name: "Paris Hilton '10", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/paris-hilton-10", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/paris-hilton2010.jpg" },
{ crime: [13] , name: "Paul Reubens", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/paul-reubens", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/reubensmug1.jpg" },
{ crime: [15] , name: "Randy Quaid", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/randy-quaid-0", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/quaidmug1.jpg" },
{ crime: [4] , name: "Reese Witherspoon", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/reese-witherspoon", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/reesewitherspoon.jpg" },
{ crime: [1] , name: "Rip Torn", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/rip-torn", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/riptornmug1.jpg" },
{ crime: [8] , name: "Robert Downey Jr.", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/robert-downey-jr", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/rdowneymug1a.jpg" },
{ crime: [17] , name: "Russell Brand", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/russell-brand", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/russellbrand2012.jpg" },
{ crime: [18] , name: "Ryan O'Neal 2/07", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/ryan-oneal-207", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/ryanonealmug1.jpg" },
{ crime: [8] , name: "Ryan O'Neal 9/08", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/ryan-oneal-908", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/ryanoneal08mug1.jpg" },
{ crime: [1] , name: "Sam Shepard", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/sam-shepard", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/samshepardmug1.jpg" },
{ crime: [9], name: "Shia LaBeouf", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/shia-labeouf", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/labeoufmug1.jpg" },
{ crime: [19] , name: "Stephen Baldwin", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/stephen-baldwin", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/stephenbaldwin.jpg" },
{ crime: [1] , name: "Steve McQueen", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/steve-mcqueen", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/mcqueenmug1.jpg" },
{ crime: [18] , name: "Terrence Howard '00", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/terrence-howard-00", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/thoward2000mug1.jpg" },
{ crime: [5] , name: "Terrence Howard '01", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/terrence-howard-01", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/thowardmug1.jpg" },
{ crime: [20] , name: "Tim Allen '78", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/tim-allen-78", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/timallen78mug1.jpg" },
{ crime: [1] , name: "Tim Allen '97", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/tim-allen-97", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/timallenmug.jpg" },
{ crime: [16] , name: "Tiny Lister", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/tiny-lister", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/tinylisterusms.jpg" },
{ crime: [18] , name: "Vince Vaughn", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/vince-vaughn", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/vvaughnmug1.jpg" },
{ crime: [19] , name: "Wesley Snipes", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/wesley-snipes", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/wesley_snipes_mug_shot_1.jpg" },
{ crime: [4] , name: "Woody Harrelson", url: "http://www.thesmokinggun.com/mugshots/celebrity/hollywood/woody-harrelson", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/woodymugshot1.jpg" },
{ crime: [20] , name: "50 Cent", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/50-cent", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/50centmug1_0.jpg" },
{ crime: [18] , name: "Akon", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/akon-0", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/akonmug1_0.jpg" },
{ crime: [6] , name: "Andre 3000", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/andre-3000", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/abenjaminmug1a.jpg" },
{ crime: [4] , name: "Axl Rose '80", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/axl-rose-80", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/axlrose.jpg" },
{ crime: [4] , name: "Axl Rose '98", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/axl-rose", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/arosemug1.jpg" },
{ crime: [8] , name: "Big Boi", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/big-boi", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/bigboi.jpg" },
{ crime: [8] , name: "Billie Holiday", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/billie-holiday", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/billieholidaymug1.jpg" },
{ crime: [1] , name: "Billie Joe Armstrong", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/billie-joe-armstrong", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/billiejoemug1.jpg" },
# { crime: [1, 8, 6, 15] , name: "Bobby Brown", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/bobby-brown", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/bbrownmug1.jpg" },
{ crime: [8] , name: "Bruno Mars", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/bruno-mars", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/brunomars.jpg" },
{ crime: [8] , name: "Buju Banton", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/buju-banton", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/buju_banton_mug_shot_1.jpg" },
{ crime: [18] , name: "Bushwick Bill", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/bushwick-bill", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/bushwickmug1.jpg" },
{ crime: [18, 4] , name: "D'Angelo", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/dangelo", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/dangelomug1.jpg" },
{ crime: [18] , name: "Da Brat", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/da-brat", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/PORTAL30.jpg" },
{ crime: [8] , name: "David BowieTSG Fav", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/david-bowie", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/bowiemug1.jpg" },
{ crime: [8] , name: "David Crosby", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/david-crosby", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/dcrosbymugshot1.jpg" },
{ crime: [6] , name: "DMX '01", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/dmx-01", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/dmxmug1.jpg" },
{ crime: [8] , name: "DMX 5/08", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/dmx-508", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/dmx082mugshot1.jpg" },
{ crime: [21] , name: "DMX 5/08", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/dmx-508-0", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/dmx08mugshot1.jpg" },
{ crime: [6] , name: "DMX 6/08", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/dmx-608", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/dmx083mugshot1.jpg" },
{ crime: [8] , name: "DMX 6/08", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/dmx-608-0", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/dmx084mugshot1.jpg" },
{ crime: [22] , name: "Donnie Wahlberg", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/donnie-wahlberg", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/wahlbergmugshot1.jpg" },
{ crime: [7] , name: "Eminem", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/eminem", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/eminemmug1.jpg" },
{ crime: [8] , name: "Fiona Apple", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/fiona-apple", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/fionaapple.jpg" },
{ crime: [6] , name: "Flavor Flav '11", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/flavor-flav", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/flavorflav.jpg" },
{ crime: [18, 5] , name: "Flavor Flav '12", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/flavor-flav-12", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/flavorflav2012.jpg" },
{ crime: [5, 14] , name: "Foxy Brown", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/foxy-brown", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/foxybrownmug1.jpg" },
# { crime:  , name: "Frank Sinatra", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/frank-sinatra", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/sinatramug1.jpg" },
# { crime:  , name: "Frankie Valli", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/frankie-valli", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/fvallimug1.jpg" },
{ crime: [1] , name: "Gary Rossington", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/gary-rossington", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/skynyrdmug1.jpg" },
{ crime: [8] , name: "George Clinton", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/george-clinton", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/gclintonmug1.jpg" },
{ crime: [1] , name: "Glen Campbell", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/glen-campbell", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/campbellnewmug1.jpg" },
{ crime: [8, 4] , name: "Glenn Frey", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/glenn-frey", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/gfreymug1.jpg" },
{ crime: [18] , name: "Hank Williams Jr.", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/hank-williams-jr", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/hankjrmug1.jpg" },
{ crime: [8] , name: "Irv Gotti", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/irv-gotti", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/irvgottimug.jpg" },
{ crime: [7, 19] , name: "Ja Rule", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/ja-rule", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/jarule.jpg" },
{ crime: [18] , name: "Jack White", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/jack-white", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/jwhitemug1.jpg" },
{ crime: [7, 18] , name: "Jamal Barrow", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/jamal-barrow", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/barrowmug1.jpg" },
{ crime: [5] , name: "James Brown '04", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/james-brown-04", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/jbrownmug1.jpg" },
{ crime: [7, 18] , name: "James Brown '88", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/james-brown-88", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/jbrown2008mug1.jpg" },
{ crime: [4] , name: "Janis Joplin", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/janis-joplin", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/janisjoplinmug1.jpg" },
{ crime: [18] , name: "Jay Z", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/jay-z", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/jayzmug1.jpg" },
{ crime: [4, 7] , name: "Jerry Lee Lewis", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/jerry-lee-lewis", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/jllewismugshot1.jpg" },
{ crime: [10] , name: "Jim Morrison", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/jim-morrison", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/morrisonmug1.jpg" },
{ crime: [20] , name: "Jimi Hendrix", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/jimi-hendrix", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/jimihendrixmug1.jpg" },
{ crime: [6] , name: "John Mayer", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/john-mayer", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/johnmayermugshot1.jpg" },
{ crime: [8] , name: "John Popper", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/john-popper", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/jpoppermug1.jpg" },
{ crime: [20] , name: "Johnny Cash", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/johnny-cash", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/jcashmug1.jpg" },
{ crime: [1, 6] , name: "Justin Bieber", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/justin-bieber", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/justinbieber.jpg" },
{ crime: [18] , name: "Kid Rock", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/kid-rock", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/kidrockmug1.jpg" },
{ crime: [9] , name: "Kurt Cobain", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/kurt-cobain", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/cobainmug1.jpg" },
{ crime: [19] , name: "Lauryn Hill", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/lauryn-hill", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/laurynhill_usms2.jpg" },
{ crime: [8] , name: "Lil Wayne", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/lil-wayne", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/lilwaynemug1.jpg" },
{ crime: [8] , name: "Lil' Kim", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/lil-kim", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/lilkimmug1.jpg" },
{ crime: [5] , name: "Lou Rawls", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/lou-rawls", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/lourawlsmug1.jpg" },
{ crime: [2] , name: "Marilyn Manson", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/marilyn-manson", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/mmanson.jpg" },
{ crime: [14] , name: "MC Hammer", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/mc-hammer", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/mchammer.jpg" },
{ crime: [13] , name: "Michael Jackson", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/michael-jackson", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/michaeljacksonmug1.jpg" },
{ crime: [8] , name: "Mick Jagger", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/mick-jagger", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/mjaggermug1.jpg" },
{ crime: [1] , name: "Nas", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/nas", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/nasmug1.jpg" },
{ crime: [7, 8] , name: "Nate Dogg", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/nate-dogg", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/halemug.jpg" },
{ crime: [6] , name: "Ne-Yo", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/ne-yo", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/neyomug1.jpg" },
{ crime: [1] , name: "Nick Carter", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/nick-carter", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/nickcartermug1.jpg" },
{ crime: [7] , name: "Nicki Minaj", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/nicki-minaj-113014", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/nickiminajmugshot.jpg" },
{ crime: [8] , name: "Ol' Dirty Bastard", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/ol-dirty-bastard", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/odbmug1.jpg" },
{ crime: [4] , name: "Ozzy Osbourne", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/ozzy-osbourne", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/Ozzymug.jpg" },
# { crime:  , name: "Patrick Stump", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/patrick-stump", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/pstumpmugshot1.jpg" },
# { crime:  , name: "Phil Spector 10/13", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/phil-spector-13", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/phillipspector102013.jpg" },
{ crime:  [23] , name: "Phil Spector 4/09", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/phil-spector-409", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/spectormugshot1.jpg" },
# { crime:  , name: "Phil Spector 6/09", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/phil-spector-609", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/phil2009spector1.jpg" },
# { crime:  , name: "Phil Spector 7/13", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/phil-spector-713", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/philspector713.jpg" },
{ crime: [13] , name: "R. Kelly", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/r-kelly", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/rkelly.jpg" },
# { crime:  , name: "Rakim", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/rakim", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/rakimmug1.jpg" },
{ crime: [4] , name: "Randy Travis 2/12", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/randy-travis-023456", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/randytravis.jpg" },
{ crime: [1] , name: "Randy Travis 8/12", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/randy-travis-812", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/randytravis2.jpg" },
{ crime: [1] , name: "Richie Sambora", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/richie-sambora", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/samboramug1.jpg" },
{ crime: [7,8] , name: "Rick Ross '08", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/rick-ross-08", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/rickrossmug1.jpg" },
{ crime: [8] , name: "Rick Ross '11", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/rick-ross-11", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/rickross2011.jpg" },
{ crime: [1] , name: "Rick Springfield", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/rick-springfield", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/rickspringfield.jpg" },
{ crime: [6] , name: "Scott Stapp", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/scott-stapp", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/stapp.jpg" },
{ crime: [5] , name: "Scott Weiland '01", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/scott-weiland-01", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/weilandmug.jpg" },
{ crime: [1] , name: "Scott Weiland '08", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/scott-weiland-08", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/weiland2008mug1.jpg" },
{ crime: [7] , name: "Sean 'Puffy' Combs", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/sean-puffy-combs", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/seancombsmug1.jpg" },
{ crime: [23] , name: "Sid Vicious", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/sid-vicious", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/sid-vicious-mugshot.jpg" },
{ crime: [7] , name: "Snoop Dogg", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/snoop-dogg", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/snoopmug1.jpg" },
{ crime: [14] , name: "Soulja Boy '09", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/soulja-boy-09", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/souljaboymug1a.jpg" },
{ crime: [7, 8] , name: "Soulja Boy '11", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/soulja-boy-11", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/souljaboy2011.jpg" },
{ crime: [8] , name: "Steven Page", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/steven-page", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/barenakedmug1.jpg" },
{ crime: [8] , name: "Steven Tyler", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/steven-tyler", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/seveventylermug.jpg" },
{ crime: [5] , name: "Suge Knight '08", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/suge-knight-08", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/sugeknight2008mug1.jpg" },
{ crime: [15] , name: "Suge Knight '97", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/suge-knight-97", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/sugeknightmugnew1.jpg" },
{ crime: [6] , name: "T-Pain", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/t-pain", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/tpainmugshot1.jpg" },
{ crime: [4,9,18] , name: "T.I.", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/ti", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/timugshot1.jpg" },
{ crime: [8] , name: "T.I. '10", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/ti-10", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/ti2010.jpg" },
{ crime: [7] , name: "The Game", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/game", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/thegamemug1.jpg" },
{ crime: [18] , name: "Tommy Lee", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/tommy-lee", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/tleemug.jpg" },
{ crime: [1, 8] , name: "Trey Anastasio '06", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/trey-anastasio-06", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/treymug1.jpg" },
{ crime: [8] , name: "Trey Anastasio '08", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/trey-anastasio-08", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/trey2008mug1.jpg" },
{ crime: [2] , name: "Tupac Shakur", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/tupac-shakur", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/tupacmug1.jpg" },
{ crime: [1] , name: "Vince Neil '07", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/vince-neil-07", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/vincenoboarder.jpg" },
{ crime: [1] , name: "Vince Neil '10", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/vince-neil-10", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/vinceneilfornewsite.jpg" },
{ crime: [8] , name: "Willie Nelson", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/willie-nelson", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/willienelsonmugshot1.jpg" },
{ crime: [8] , name: "Wiz Khalifa", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/wiz-khalifa", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/wizkhalifa.jpg" },
{ crime: [1] , name: "Wynonna Judd", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/wynonna-judd", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/wynonnajuddmug1.jpg" },
{ crime: [5] , name: "Yanni", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/yanni", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/yannimug1.jpg" },
{ crime: [7] , name: "Young Jeezy", url: "http://www.thesmokinggun.com/mugshots/celebrity/music/young-jeezy", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/youngjeezymug1.jpg" },
# { crime:  , name: "'Dog' Chapman '03", url: "http://www.thesmokinggun.com/mugshots/celebrity/television/duane-dog-chapman", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/dogchapmanmug1.jpg" },
{ crime: [1] , name: "'Dog' Chapman '76", url: "http://www.thesmokinggun.com/mugshots/celebrity/television/duane-dog-chapman-76", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/dogchapman.jpg" },
{ crime: [8] , name: "Chace Crawford", url: "http://www.thesmokinggun.com/mugshots/celebrity/television/chace-crawford", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/chace_crawford_mug_shot_1.jpg" },
{ crime: [1] , name: "Chris Kattan", url: "http://www.thesmokinggun.com/mugshots/celebrity/television/chris-kattan", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/chriskattan.jpg" },
# { crime:  , name: "Dana Plato", url: "http://www.thesmokinggun.com/mugshots/celebrity/television/dana-plato", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/platomug1.jpg" },
{ crime: [1] , name: "David Cassidy '10", url: "http://www.thesmokinggun.com/mugshots/celebrity/television/david-cassidy", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/davidcassidy.jpg" },
{ crime: [1] , name: "David Cassidy '13", url: "http://www.thesmokinggun.com/mugshots/celebrity/television/david-cassidy-13", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/davidcassidy2013.jpg" },
{ crime: [8] , name: "David Faustino", url: "http://www.thesmokinggun.com/mugshots/celebrity/television/david-faustino", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/faustinomug1.jpg" },
{ crime: [6] , name: "Dawn Wells", url: "http://www.thesmokinggun.com/mugshots/celebrity/television/dawn-wells", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/dawnwellsmug1.jpg" },
{ crime: [5] , name: "Gary Coleman", url: "http://www.thesmokinggun.com/mugshots/celebrity/television/gary-coleman", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/garycolemanmug1.jpg" },
{ crime: [8] , name: "Gary Dourdan", url: "http://www.thesmokinggun.com/mugshots/celebrity/television/gary-dourdan", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/garydourdanmug1.jpg" },
{ crime: [1] , name: "Heather Locklear", url: "http://www.thesmokinggun.com/mugshots/celebrity/television/heather-locklear", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/hlocklearmugshot1.jpg" },
{ crime: [1] , name: "Jaime Pressly", url: "http://www.thesmokinggun.com/mugshots/celebrity/television/jaime-pressly", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/jaimepresslymug.jpg" },
{ crime: [1] , name: "Joseph Gannascoli", url: "http://www.thesmokinggun.com/mugshots/celebrity/television/joseph-gannascoli", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/gannascolimug1.jpg" },
{ crime: [18] , name: "Joshua Jackson", url: "http://www.thesmokinggun.com/mugshots/celebrity/television/joshua-jackson", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/joshjacksonmug1.jpg" },
{ crime: [1] , name: "Joyce DeWitt", url: "http://www.thesmokinggun.com/mugshots/celebrity/television/joyce-dewitt", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/jdewittmugshot1.jpg" },
{ crime: [1] , name: "Kim Delaney", url: "http://www.thesmokinggun.com/mugshots/celebrity/television/kim-delaney", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/delaneymug.jpg" },
{ crime: [16] , name: "Larry King", url: "http://www.thesmokinggun.com/mugshots/celebrity/television/larry-king", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/larrykingmug1.jpg" },
{ crime: [1] , name: "Matthew Fox", url: "http://www.thesmokinggun.com/mugshots/celebrity/television/matthew-fox", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/matthewfox.jpg" },
{ crime: [1] , name: "Mike Lookinland", url: "http://www.thesmokinggun.com/mugshots/celebrity/television/mike-lookinland", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/lookinlandmug.jpg" },
{ crime: [1] , name: "Mischa Barton", url: "http://www.thesmokinggun.com/mugshots/celebrity/television/mischa-barton", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/mbartonmug1.jpg" },
{ crime: [3, 8] , name: "Robert Iler", url: "http://www.thesmokinggun.com/mugshots/celebrity/television/robert-iler", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/ilermug1.jpg" },
{ crime: [1] , name: "Sally Struthers", url: "http://www.thesmokinggun.com/mugshots/celebrity/television/sally-struthers", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/sallystruthers.jpg" },
# { crime: 18 , name: "Shepard Smith", url: "http://www.thesmokinggun.com/mugshots/celebrity/television/shepard-smith", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/dsmithmug.jpg" },
{ crime: [4] , name: "Snooki", url: "http://www.thesmokinggun.com/mugshots/celebrity/television/snooki", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/snookisized.jpg" },
{ crime: [10] , name: "Steve-O", url: "http://www.thesmokinggun.com/mugshots/celebrity/television/steve-o", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/steveomug1.jpg" },
{ crime: [16] , name: "Suzanne Somers", url: "http://www.thesmokinggun.com/mugshots/celebrity/television/suzanne-somers", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/ssomersmugshot1.jpg" },
# { crime:  , name: "The "Lost" Girls", url: "http://www.thesmokinggun.com/mugshots/celebrity/television/lost-girls", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/lostgirlsmug1.jpg" },
{ crime: [18, 11] , name: "The 'ShamWow' Guy", url: "http://www.thesmokinggun.com/mugshots/celebrity/television/shamwow-guy", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/shlomimugshot1.jpg" },
{ crime: [1] , name: "Tracey Gold", url: "http://www.thesmokinggun.com/mugshots/celebrity/television/tracey-gold", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/tgoldmug1.jpg" },
{ crime: [8] , name: "Yasmine Bleeth", url: "http://www.thesmokinggun.com/mugshots/celebrity/television/yasmine-bleeth", image: "http://www.thesmokinggun.com/sites/default/files/imagecache/670xX/photos/bleethmug.jpg" },
]

artists_list.each do |artist|
		artist[:crime].each do |crime|
			@crime = Crime.find(crime)
			@crime.artists.create!(name: artist[:name],
													url: artist[:url],
													image: artist[:image])
		end
end